authentication/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("sitepages.urls", namespace="sitepages")),
    path('', include("authentication.urls", namespace="authentication")),
    
    path('ckeditor/', include('ckeditor_uploader.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sitepages/urls.py
from django.urls import path, include
from django.conf.urls import handler404
from .views import *



app_name = "sitepages"

urlpatterns = [
    path('', Home, name='home'),
    path('product/', product_list, name='productlist'),
    path('product/<pro_id>/', product_detail, name='product_det'),
    
    ######### Category #####
      
    path('category/', category, name='category'),
    path('category/<cat_id>/', category_product, name='categorycid'),
    
    ######### Vendor #####
    
    path('vendor/', vendor_list, name='vendor'),
    path('vendor/<ven_id>/', vendor_detail, name='vendor_det'),
    
    ######### Tags #####
    path('product/tag/<slug:tag_slug>/', tag, name='tag'),
    
    ######### Add review #####
    path('review/<str:pro_id>/', reviewform, name='review'),
    
    ######### Search #####
    path('search/', search, name='search'),
    
    ######### Add to Cart #####
    path('add_to_cart/', add_to_cart, name='add_to_cart'),
    path('cart/', cart_view, name='cart'),
    
    ######### Delete item from Cart #####
    path('delete_from_cart/', delete_cart, name='delete_from_cart'),
    
    ######### Update Cart #####
    path('update_cart/', update_cart, name='update_cart'),
    
    ######### Checkout #####
    path('checkout/', checkout, name='checkout'),
    
    ######### Paypal #####
    path('paypal/', include('paypal.standard.ipn.urls')),
    
    ######### Payment successful #####
    path('payment_completed/', payment_complete_view, name='payment_completed'),
    
    ######### Payment failed #####
    path('payment_failed/', payment_failed_view, name='payment_failed'),
    
    ######### Dashboard #####
    path('dashboard/', dashboard, name='dashboard'),
    
    ######### Dashboard Order #####
    path('dashboard/order/<int:id>', order_detail, name='order'),
    
    ######### Making Address default  #####
    path('default-address/', default_address, name='default-address'),
    
    ######### Wishlist  #####
    path('wishlist/', wishlist, name='wishlist'),
    
    ######### Adding to Wishlist  #####
    path('add-to-wishlist/', add_to_wishlist, name='add-to-wishlist'),
    
    ######### Removing from Wishlist  #####
    path('remove-from-wishlist/', remove_wishlist, name='remove-from-wishlist'),
    
    ######### Editing profile  #####
    path('profile-edit/', profile_edit, name='profile-edit'),
    
    ######### About Page  #####
    path('about/', about, name='about'),
    
    ######### 404 Page  #####
    path('404/', custom_404, name='404'),
]

    

templates/category_product.html
{% extends 'base.html' %}
{% load static %}


{% block catlist_content %}

<!DOCTYPE html>
<html lang="en">





        

        <main class="main">
        	<div class="page-header text-center" style="background-image: url('{%static 'assets/images/page-header-bg.jpg'%}')">
        		<div class="container">
        			<h1 class="page-title">{{ category.title }}<span>We found <strong>( {{ products.count }} )</strong> item{{ products.count|pluralize }} for you.</span></h1>
        		</div><!-- End .container -->
        	</div><!-- End .page-header -->
            

            <div class="page-content">
                <div class="container">
                	<div class="row">
                		<div class="col-lg-9">
                			<div class="toolbox">
                				<div class="toolbox-left">
                					<div class="toolbox-info">
                						Showing <span>9 of 56</span> Products
                					</div><!-- End .toolbox-info -->
                				</div><!-- End .toolbox-left -->

                				<div class="toolbox-right">
                					<div class="toolbox-sort">
                						<label for="sortby">Sort by:</label>
                						<div class="select-custom">
											<select name="sortby" id="sortby" class="form-control">
												<option value="popularity" selected="selected">Most Popular</option>
												<option value="rating">Most Rated</option>
												<option value="date">Date</option>
											</select>
										</div>
                					</div><!-- End .toolbox-sort -->
                					<div class="toolbox-layout">
                						<a href="#" class="btn-layout active">
                							<svg width="16" height="10">
                								<rect x="0" y="0" width="4" height="4" />
                								<rect x="6" y="0" width="10" height="4" />
                								<rect x="0" y="6" width="4" height="4" />
                								<rect x="6" y="6" width="10" height="4" />
                							</svg>
                						</a>

                						<a href="#" class="btn-layout">
                							<svg width="10" height="10">
                								<rect x="0" y="0" width="4" height="4" />
                								<rect x="6" y="0" width="4" height="4" />
                								<rect x="0" y="6" width="4" height="4" />
                								<rect x="6" y="6" width="4" height="4" />
                							</svg>
                						</a>

                						<a href="#" class="btn-layout">
                							<svg width="16" height="10">
                								<rect x="0" y="0" width="4" height="4" />
                								<rect x="6" y="0" width="4" height="4" />
                								<rect x="12" y="0" width="4" height="4" />
                								<rect x="0" y="6" width="4" height="4" />
                								<rect x="6" y="6" width="4" height="4" />
                								<rect x="12" y="6" width="4" height="4" />
                							</svg>
                						</a>

                						<a href="#" class="btn-layout">
                							<svg width="22" height="10">
                								<rect x="0" y="0" width="4" height="4" />
                								<rect x="6" y="0" width="4" height="4" />
                								<rect x="12" y="0" width="4" height="4" />
                								<rect x="18" y="0" width="4" height="4" />
                								<rect x="0" y="6" width="4" height="4" />
                								<rect x="6" y="6" width="4" height="4" />
                								<rect x="12" y="6" width="4" height="4" />
                								<rect x="18" y="6" width="4" height="4" />
                							</svg>
                						</a>
                					</div><!-- End .toolbox-layout -->
                				</div><!-- End .toolbox-right -->
                			</div><!-- End .toolbox -->
                             {% for p in products %}
                            <div class="products mb-3">
                                <div class="product product-list">
                                    <div class="row">
                                        <div class="col-6 col-lg-3">
                                            <figure class="product-media">
                                                <span class="product-label label-new">New</span>
                                                <a href="{% url 'sitepages:product_det' p.pro_id %}">
                                                    <img src="{{ p.image.url }}" alt="Product image" class="product-image">
                                                </a>
                                            </figure><!-- End .product-media -->
                                        </div><!-- End .col-sm-6 col-lg-3 -->

                                        <div class="col-6 col-lg-3 order-lg-last">
                                            <div class="product-list-action">
												<h3 class="product-title"><a href="#">{{ p.title }}</a></h3><!-- End .product-title -->
                                                <div class="product-price">
                                                    ${{ p.price }}
                                                </div><!-- End .product-price -->
                                                <div class="ratings-container">
                                                    <div class="ratings">
                                                        <div class="ratings-val" style="width: 20%;"></div><!-- End .ratings-val -->
                                                    </div><!-- End .ratings -->
                                                    <span class="ratings-text">( 2 Reviews )</span>
                                                </div><!-- End .rating-container -->

                                                <div class="product-action">
                                                    <a href="popup/quickView.html" class="btn-product btn-quickview" title="Quick view"><span>quick view</span></a>
                                                    <a href="#" class="btn-product btn-compare" title="Compare"><span>compare</span></a>
                                                </div><!-- End .product-action -->

                                                <a href="#" class="btn-product btn-cart"><span>add to cart</span></a>
                                            </div><!-- End .product-list-action -->
                                        </div><!-- End .col-sm-6 col-lg-3 -->

                                        
                                    </div><!-- End .row -->
                                </div><!-- End .product -->

                                
                            </div><!-- End .products -->
                            {% endfor %}

                			<nav aria-label="Page navigation">
							    <ul class="pagination">
							        <li class="page-item disabled">
							            <a class="page-link page-link-prev" href="#" aria-label="Previous" tabindex="-1" aria-disabled="true">
							                <span aria-hidden="true"><i class="icon-long-arrow-left"></i></span>Prev
							            </a>
							        </li>
							        <li class="page-item active" aria-current="page"><a class="page-link" href="#">1</a></li>
							        <li class="page-item"><a class="page-link" href="#">2</a></li>
							        <li class="page-item"><a class="page-link" href="#">3</a></li>
							        <li class="page-item-total">of 6</li>
							        <li class="page-item">
							            <a class="page-link page-link-next" href="#" aria-label="Next">
							                Next <span aria-hidden="true"><i class="icon-long-arrow-right"></i></span>
							            </a>
							        </li>
							    </ul>
							</nav>
                		</div><!-- End .col-lg-9 -->
                		<aside class="col-lg-3 order-lg-first">
                			<div class="sidebar sidebar-shop">
                				<div class="widget widget-clean">
                					<label>Filters:</label>
                					<a href="#" class="sidebar-filter-clear">Clean All</a>
                				</div><!-- End .widget widget-clean -->

                				

        						<div class="widget widget-collapsible">
    								<h3 class="widget-title">
									    <a data-toggle="collapse" href="#widget-3" role="button" aria-expanded="true" aria-controls="widget-3">
									        Colour
									    </a>
									</h3><!-- End .widget-title -->

									<div class="collapse show" id="widget-3">
										<div class="widget-body">
											<div class="filter-colors">
												<a href="#" style="background: #b87145;"><span class="sr-only">Color Name</span></a>
												<a href="#" style="background: #f0c04a;"><span class="sr-only">Color Name</span></a>
												<a href="#" style="background: #333333;"><span class="sr-only">Color Name</span></a>
												<a href="#" class="selected" style="background: #cc3333;"><span class="sr-only">Color Name</span></a>
												<a href="#" style="background: #3399cc;"><span class="sr-only">Color Name</span></a>
												<a href="#" style="background: #669933;"><span class="sr-only">Color Name</span></a>
												<a href="#" style="background: #f2719c;"><span class="sr-only">Color Name</span></a>
												<a href="#" style="background: #ebebeb;"><span class="sr-only">Color Name</span></a>
											</div><!-- End .filter-colors -->
										</div><!-- End .widget-body -->
									</div><!-- End .collapse -->
        						</div><!-- End .widget -->

        						<div class="widget widget-collapsible">
    								<h3 class="widget-title">
									    <a data-toggle="collapse" href="#widget-4" role="button" aria-expanded="true" aria-controls="widget-4">
									        Brand
									    </a>
									</h3><!-- End .widget-title -->

									<div class="collapse show" id="widget-4">
										<div class="widget-body">
											<div class="filter-items">
												<div class="filter-item">
													<div class="custom-control custom-checkbox">
														<input type="checkbox" class="custom-control-input" id="brand-1">
														<label class="custom-control-label" for="brand-1">Apple</label>
													</div><!-- End .custom-checkbox -->
												</div><!-- End .filter-item -->

												

											</div><!-- End .filter-items -->
										</div><!-- End .widget-body -->
									</div><!-- End .collapse -->
        						</div><!-- End .widget -->

        						<div class="widget widget-collapsible">
    								<h3 class="widget-title">
									    <a data-toggle="collapse" href="#widget-5" role="button" aria-expanded="true" aria-controls="widget-5">
									        Price
									    </a>
									</h3><!-- End .widget-title -->

									<div class="collapse show" id="widget-5">
										<div class="widget-body">
                                            <div class="filter-price">
                                                <div class="filter-price-text">
                                                    Price Range:
                                                    <span id="filter-price-range"></span>
                                                </div><!-- End .filter-price-text -->

                                                <div id="price-slider"></div><!-- End #price-slider -->
                                            </div><!-- End .filter-price -->
										</div><!-- End .widget-body -->
									</div><!-- End .collapse -->
        						</div><!-- End .widget -->
                			</div><!-- End .sidebar sidebar-shop -->
                		</aside><!-- End .col-lg-3 -->
                	</div><!-- End .row -->
                </div><!-- End .container -->
            </div><!-- End .page-content -->
        </main><!-- End .main -->

        
    </div><!-- End .page-wrapper -->
    <button id="scroll-top" title="Back to Top"><i class="icon-arrow-up"></i></button>

    <!-- Mobile Menu -->
    <div class="mobile-menu-overlay"></div><!-- End .mobil-menu-overlay -->


    

    
{% endblock %}

templates/checkout.html
{% extends 'base.html' %}

{% load static %}

{% block cart_content %}




        <main class="main">
        	<div class="page-header text-center" style="background-image: url('assets/images/page-header-bg.jpg')">
        		<div class="container">
        			<h1 class="page-title">Checkout<span>There are ( {{ totalcartitems }} ) product{{ totalcartitems|pluralize }}</span></h1>
        		</div><!-- End .container -->
        	</div><!-- End .page-header -->
            <nav aria-label="breadcrumb" class="breadcrumb-nav">
                <div class="container">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item"><a href="index.html">Home</a></li>
                        <li class="breadcrumb-item"><a href="#">Shop</a></li>
                        <li class="breadcrumb-item active" aria-current="page">Checkout</li>
                    </ol>
                </div><!-- End .container -->
            </nav><!-- End .breadcrumb-nav -->

            <div class="page-content">
            	<div class="checkout">
	                <div class="container">
            			<div class="checkout-discount">
            				<form action="#">
        						<input type="text" class="form-control" required id="checkout-discount-input">
            					<label for="checkout-discount-input" class="text-truncate">Have a coupon? <span>Click here to enter your code</span></label>
            				</form>
            			</div><!-- End .checkout-discount -->
            			<form action="#">
		                	<div class="row">
		                		<div class="col-lg-9">
		                			<h2 class="checkout-title">Billing Details</h2><!-- End .checkout-title -->
		                				<div class="row">
		                					<div class="col-sm-6">
		                						<label>First Name *</label>
		                						<input type="text" class="form-control" required value="{{ request.user.username|title  }}">
		                					</div><!-- End .col-sm-6 -->

		                					<div class="col-sm-6">
		                						<label>Mobile *</label>
		                						<input type="text" class="form-control" required value="{{ active_address.mobile }}">
		                					</div><!-- End .col-sm-6 -->
		                				</div><!-- End .row -->

	            						<label>Company Name (Optional)</label>
	            						<input type="text" class="form-control">

	            						<label>Country *</label>
										<select name="" id="country">
											<option value="Nigeria">Nigeria</option>
											<option value="UK">UK</option>
											<option value="USA">USA</option>
											<option value="France">France</option>
										</select>
	            						<input type="text" class="form-control" required for="country">

	            						<label>Address *</label>
	            						<input type="text" class="form-control" placeholder="House number and Street name" required value="{{ active_address.address }}">
	            						<input type="text" class="form-control" placeholder="Appartments, suite, unit etc ..." required>


	                					<label>Order notes (optional)</label>
	        							<textarea class="form-control" cols="30" rows="4" placeholder="Notes about your order, e.g. special notes for delivery"></textarea>
		                		</div><!-- End .col-lg-9 -->
		                		<aside class="col-lg-3" style="overflow: hidden;">
		                			<div class="summary">
		                				<h3 class="summary-title">Your Order</h3><!-- End .summary-title -->

		                				<table class="table table-summary">
		                					<thead>
		                						<tr>
		                							<th>Product</th>
		                							<th>Total</th>
		                						</tr>
		                					</thead>

		                					<tbody>
                                                {% for pro_id, item in cart_data.items %}
                                                
		                						<tr>
                                                    
		                							<td>
                                                        <a href="{% url 'sitepages:product_det' item.pid %}">
															<img src="{{ item.image }}" alt="Product image">
														</a>
                                                        <a href="{% url 'sitepages:product_det' item.pid %}">{{ item.title }}</a>
                                                        <p>${{ item.price }}</p>
                                                        <p>{{ item.qty }}</p>
                                                    </td>
		                							<td>${% widthratio item.price 1 item.qty %}</td>
		                						</tr>
                                                {% endfor %}

		                						
		                						<tr class="summary-subtotal">
		                							<td>Subtotal:</td>
		                							<td>${{ cart_total_amount|floatformat:2 }}</td>
		                						</tr><!-- End .summary-subtotal -->
		                						<tr>
		                							<td>Shipping:</td>
		                							<td>Free shipping</td>
		                						</tr>
		                						<tr class="summary-total">
		                							<td>Total:</td>
		                							<td>${{ cart_total_amount|floatformat:2 }}</td>
		                						</tr><!-- End .summary-total -->
		                					</tbody>
		                				</table><!-- End .table table-summary -->

		                				<div class="accordion-summary" id="accordion-payment">
										    <div class="card">
										        <div class="card-header" id="heading-1">
										            <h2 class="card-title">
										                <a role="button" data-toggle="collapse" href="#collapse-1" aria-expanded="true" aria-controls="collapse-1">
										                    Direct bank transfer
										                </a>
										            </h2>
										        </div><!-- End .card-header -->
										        <div id="collapse-1" class="collapse show" aria-labelledby="heading-1" data-parent="#accordion-payment">
										            <div class="card-body">
										                Make your payment directly into our bank account. Please use your Order ID as the payment reference. Your order will not be shipped until the funds have cleared in our account.
										            </div><!-- End .card-body -->
										        </div><!-- End .collapse -->
										    </div><!-- End .card -->

										    <div class="card">
										        <div class="card-header" id="heading-2">
										            <h2 class="card-title">
										                <a class="collapsed" role="button" data-toggle="collapse" href="#collapse-2" aria-expanded="false" aria-controls="collapse-2">
										                    Check payments
										                </a>
										            </h2>
										        </div><!-- End .card-header -->
										        <div id="collapse-2" class="collapse" aria-labelledby="heading-2" data-parent="#accordion-payment">
										            <div class="card-body">
										                Ipsum dolor sit amet, consectetuer adipiscing elit. Donec odio. Quisque volutpat mattis eros. Nullam malesuada erat ut turpis. 
										            </div><!-- End .card-body -->
										        </div><!-- End .collapse -->
										    </div><!-- End .card -->

										    <div class="card">
										        <div class="card-header" id="heading-3">
										            <h2 class="card-title">
										                <a class="collapsed" role="button" data-toggle="collapse" href="#collapse-3" aria-expanded="false" aria-controls="collapse-3">
										                    Cash on delivery
										                </a>
										            </h2>
										        </div><!-- End .card-header -->
										        <div id="collapse-3" class="collapse" aria-labelledby="heading-3" data-parent="#accordion-payment">
										            <div class="card-body">Quisque volutpat mattis eros. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Donec odio. Quisque volutpat mattis eros. 
										            </div><!-- End .card-body -->
										        </div><!-- End .collapse -->
										    </div><!-- End .card -->

										    <div class="card">
										        <div class="card-header" id="heading-4">
										            <h2 class="card-title">
										                <a class="collapsed" role="button" data-toggle="collapse" href="#collapse-4" aria-expanded="false" aria-controls="collapse-4">
										                    PayPal <small class="float-right paypal-link">What is PayPal?</small>
										                </a>
										            </h2>
										        </div><!-- End .card-header -->
										        <div id="collapse-4" class="collapse" aria-labelledby="heading-4" data-parent="#accordion-payment">
										            <div class="card-body">
										                Nullam malesuada erat ut turpis. Suspendisse urna nibh, viverra non, semper suscipit, posuere a, pede. Donec nec justo eget felis facilisis fermentum.
										            </div><!-- End .card-body -->
										        </div><!-- End .collapse -->
										    </div><!-- End .card -->

										    <div class="card">
										        <div class="card-header" id="heading-5">
										            <h2 class="card-title">
										                <a class="collapsed" role="button" data-toggle="collapse" href="#collapse-5" aria-expanded="false" aria-controls="collapse-5">
										                    Credit Card (Stripe)
										                    <img src="{% static 'assets/images/payments-summary.png' %}" alt="payments cards">
										                </a>
										            </h2>
										        </div><!-- End .card-header -->
										        <div id="collapse-5" class="collapse" aria-labelledby="heading-5" data-parent="#accordion-payment">
										            <div class="card-body"> Donec nec justo eget felis facilisis fermentum.Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Donec odio. Quisque volutpat mattis eros. Lorem ipsum dolor sit ame.
										            </div><!-- End .card-body -->
										        </div><!-- End .collapse -->
										    </div><!-- End .card -->
										</div><!-- End .accordion -->

		                				<button type="submit" class="btn btn-outline-primary-2 btn-order btn-block">
		                					<span class="btn-text">{{ paypal_payment_button.render }}</span>
		                					<span class="btn-hover-text">{{ paypal_payment_button.render }}</span>
		                				</button>
		                			</div><!-- End .summary -->
		                		</aside><!-- End .col-lg-3 -->
		                	</div><!-- End .row -->
            			</form>
	                </div><!-- End .container -->
                </div><!-- End .checkout -->
            </div><!-- End .page-content -->
        </main><!-- End .main -->

  {% endblock %}      

templates/payment-failed.html
{% extends 'base.html' %}

{% load static %}

{% block cart_content %}



<section class="payment-failed">
    <div class="content">
        <h2>Payment Failed

        </h2>
        <img src="{% static 'assets/images/IMG_0604 3.PNG' %}" alt="Payment Failed">
        <p>It looks like there was an error processing your payment. Please check your card details and try again.</p>
        <button class="btn">Try Again</button>
    </div>
</section>

{% endblock %}

templates/vendor.html
{% extends 'base.html' %}
{% load static %}


{% block ven_content %}


        <main class="main">
        	<div class="page-header text-center" style="background-image: url('{% static 'assets/images/page-header-bg.jpg'%}')">
        		<div class="container">
        			<h1 class="page-title">Vendors<span>We have <strong>( {{ vendor.count }} ) vendor{{ vendor.count|pluralize }}.</strong></span></h1>
        		</div><!-- End .container -->
        	</div><!-- End .page-header -->
            

            <div class="page-content">
                <div class="container">
                	
                     
                	<div class="row">
                        {% for v in vendor %}
                		<div class="col-6 col-md-4 col-lg-4">
                			<div class="product text-center">
                				<figure class="product-media">
                					<!-- <span class="product-label label-sale">30% off</span> -->
                					<a href="{% url 'sitepages:vendor_det' v.ven_id %}">
                						<img src="{{ v.image.url }}" alt="Product image" class="product-image">
                					</a>

                					
                				</figure><!-- End .product-media -->

                				<div class="product-body">
                					
                					<h3 class="product-title"><a href="{% url 'sitepages:vendor_det' v.ven_id %}">{{ v.title }}</a></h3><!-- End .product-title -->
                					<div class="product-price">
                						<span class="new-price">{{ v.vendor.all.count }}</span>
                						
                					</div><!-- End .product-price -->
                                    <div class="product-size">
                                        <p>{{ v.date|date }}</p>
                                    </div><!-- End .product-size -->
                					<div class="#">
                						<p class="ratings-text">{{ v.address }}</p>
                						
                						<span class="ratings-text">{{ v.contact }}</span>
                					</div><!-- End .rating-container -->

                					
                				</div><!-- End .product-body -->
                			</div><!-- End .product -->
                		</div><!-- End .col-sm-6 col-lg-4 -->
                        {% endfor %}

                		
                	</div><!-- End .row -->

                	
                	
            </div><!-- End .page-content -->


        </main><!-- End .main -->

        
    </div><!-- End .page-wrapper -->
    <button id="scroll-top" title="Back to Top"><i class="icon-arrow-up"></i></button>

    

    

   

    

{% endblock %}